# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170623_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 22, 19, 24, 29, 966687, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
